<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SentenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SentenceRepository extends EntityRepository
{
}
